export const avatar = [
    {
      id: "1",
      username: "testuser",
      image: "https://picsum.photos/id/237/200/200",
      company: "Work at Ledner - Kris",
    },
    {
      id: "2",
      username: "asafasaasc",
      image: "https://picsum.photos/id/236/200/200",
      company: "Work at Feeney, Abshire and Tromp",
    },
    {
      id: "3",
      username: "sadcasca",
      image: "https://picsum.photos/id/238/200/200",
      company: "Work at Wunsch Inc",
    },
    {
      id: "4",
      username: "sdsacasca",
      image: "https://picsum.photos/id/239/200/200",
      company: "Work at Rutherford - Rohan",
    },
    {
      id: "5",
      username: "xaxxsxa",
      image: "https://picsum.photos/id/227/200/200",
      company: "Work at Moen - Hirthe",
    },
    {
      id: "6",
      username: "asd_sksc_s",
      image: "https://picsum.photos/id/229/200/200",
      company: "Work at Wunsch Inc",
    },
    {
      id: "7",
      username: "ascsama",
      image: "https://picsum.photos/id/247/200/200",
      company: "Work at Upton - Gislason",
    },
    {
      id: "8",
      username: "Paige60",
      image: "https://picsum.photos/id/257/200/200",
      company: "Work at Moen - Hirthe",
    },
    {
      id: "9",
      username: "Rollin96",
      image: "https://picsum.photos/id/256/200/200",
      company: "Work at Wunsch Inc",
    },
    {
      id: "10",
      username: "Carolyn31",
      image: "https://picsum.photos/id/267/200/200",
      company: "Work at Upton - Gislason",
    },
    {
      id: "11",
      username: "Luz57",
      image: "https://picsum.photos/id/266/200/200",
      company: "Work at Moen - Hirthe",
    },
    {
      id: "12",
      username: "Roger51",
      image: "https://picsum.photos/id/261/200/200",
      company: "Work at Upton - Gislason",
    },
    {
      id: "13",
      username: "Zita_Berge",
      image: "https://picsum.photos/id/260/200/200",
      company: "Work at Moen - Hirthe",
    },
  ];